### ISSUE TITLE
Deletes not detected?

### ISSUE THREAD

**Issue by rothschild86** [3Squared/ActiveAndroid-Loaders#1]
Hey man! Nice code. Got a little problem with deletes not triggering a reset (adds work nicely and show right up). Tried both Delete() and Select().executeSingle.delete() syntaxes. Would you have any insight on where to troubleshoot?

**Comment by blork** [comment]
Hi! Thanks for taking a look. I can't seem to replicate the problem you're having - the loaders stay up to date with deletions in my testing. What version of Android are you trying it with?

I've just pushed an example project, take a look and see if it works for you.

**Comment by rothschild86** [comment]
Hey! Thanks for the juicy example. Yeah, all seems to work in your code. At least now I know it is on my end (Happens on both android 2 and 4, using compatibility load manager). My inserts/deletes happen in a different fragment. When I pop the backstack to go the list fragment, inserts appear, but deletes do not disappear. Is it too much too ask for sync to work when performing actions in a different fragment?

**Comment by blork** [comment]
It should work fine between fragments - I'm not sure what the problem could be. Could you post some example code or perhaps upload your project somewhere so I can take a look? Thanks!

**Comment by rothschild86** [comment]
I have since then implemented the same pattern (inserts/deletes happen in a different fragment) on a different entity and everything works perfect. so for all intents, I can't even replicate the problem in the new code at the moment. Deletes should be rare for this specific entity, so I'll just chalk it up to black magic for now :) Thanks man. Cheers!
