### ISSUE TITLE
Deletes don't trigger?

### ISSUE THREAD

**Issue by rothschild86** [3Squared/ActiveAndroid-Loaders#2]
Very nice AA extension! Thank you for making it available. In my experience inserts and updates trigger refresh just fine, but deletes don't. Specifically, I'm using "new Delete().From().execute()" Has anybody else noticed problems with deletes?

**Comment by blork** [comment]
Thanks! I haven't noticed this problem, but most of the time I'm calling `.delete()` on an object rather than using `new Delete()`. Could you make a sample project that demonstrates the problem?

**Comment by blork** [comment]
Ah, it seems this is a bug in ActiveAndroid, see this issue: https://github.com/pardom/ActiveAndroid/pull/185
You may have to build a new version of AA yourself which includes this fix.

**Comment by rothschild86** [comment]
Nice detective work. I'm sorry for assuming the problem was in your lib. Cheers!

**Comment by blork** [comment]
No worries, always nice to see someone using it!
